os: WMF 5

environment:
  GitHubToken:
    secure: 
  PSGalleryKey:
    secure:

install:
  - ps: Install-PackageProvider NuGet -Scope CurrentUsert
  - ps: Install-Module Pester -Scope CurrentUsert
  - ps: Install-Module PSScriptAnalyzer -Scope CurrentUsert
  - ps: Install-Module DevTools -Scope CurrentUsert

before_build:
  - WhoAmI
  - ps: dt Shortcuts
  - ps: Uninstall-Module DevTools

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup