#Use default VM it'll speed up the process a lot!
#os: WMF 5

version: '{build}'

skip_commits:
  message: /docs/
  
platform:
  - x64
#  - x86
  
init:
  - WhoAmI
  
install:
  - cinst Pester -version 3.4.3
#  - ps: Install-PackageProvider NuGet -Force | Out-Null
#  - ps: Install-Module Pester -RequiredVersion 3.4.3 -Force

before_build:
  - cmd: set PS_PROFILE=%userprofile%\Documents\WindowsPowerShell\Modules\%APPVEYOR_PROJECT_NAME%
  - cmd: mklink /J %PS_PROFILE% %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { dt Build }

test_script:
#  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile ".\TestsResults.xml" -PassThru
#  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
#  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_PROJECT_NAME) release $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: $(APPVEYOR_PROJECT_NAME)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
