os: WMF 5

version: '{build}'

platform:
  - x86
  - x64
  
environment:
  gitHubToken:
    secure: 
  psGalleryKey:
    secure:
  
init:
  - WhoAmI
  
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
#  - ps: Install-Module Pester -Force
#  - ps: Install-Module PSScriptAnalyzer -Force
  - ps: Install-Module DevTools -Force

before_build:
  - ps: dt Shortcuts
  - ps: Uninstall-Module $env:APPVEYOR_PROJECT_NAME

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup
  
build: off

branches:
  only:
    - master