os: WMF 5

environment:
  GitHubToken:
    secure: 
  PSGalleryKey:
    secure:

install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

version: '{build}'

before_build:
  - whoami
  - cmd: mklink /J C:\Users\appveyor\Documents\WindowsPowerShell\Modules\devtools c:\projects\devtools
  - ps: dt Shortcuts

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup