os: WMF 5

version: '{build}'

platform:
  - x86
  
environment:
  releaseDescription : true
  psGalleryKey:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  
init:
  - WhoAmI

install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module DevTools -Force
#  - ps: Install-Module Debug -Force

before_build:
  - ps: dt Shortcuts
  - ps: Uninstall-Module DevTools

build_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { dt Build }
  - ps: Write-Host $env:APPVEYOR_REPO_TAG

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup
  
build: on

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(releaseDescription)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: $(APPVEYOR_PROJECT_NAME)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true