os: WMF 5

version: '{build}'

platform:
  - x86
#  - x64

skip_commits:
  message: /Docs/
  
init:
  - WhoAmI

install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module Pester -Force
#  - ps: Install-Module DevTools -Force

before_build:
  #- ps: dt Install
  #- ps: Uninstall-Module DevTools
  - cmd: mklink /J C:\Users\AppVeyor\Documents\WindowsPowerShell\Modules\DevTools c:\projects\DevTools

build_script:
  #- ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { dt Build }
  - ps: dt Build

test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  # - ps: dt Test
  # - ps: .\Test.ps1
  
after_test:
  - ps: dt Cleanup
  
build: on

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_PROJECT_NAME) release $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: $(APPVEYOR_PROJECT_NAME)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true