os: WMF 5

version: '{build}'

platform:
  - x86
#  - x64
  
environment:
  gitHubToken:
    secure: 
  psGalleryKey:
    secure:
  
init:
  - WhoAmI
  
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
#  - ps: Install-Module Pester -Force
#  - ps: Install-Module PSScriptAnalyzer -Force
  - ps: Install-Module DevTools -Force

before_build:
  - ps: dt Shortcuts
  - ps: Uninstall-Module DevTools

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup
  
build: on

branches:
  only:
    - master
    
deploy:
  release: $(RELEASE_VERSION)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: devtools-$(RELEASE_VERSION).zip
  draft: false
  prerelease: false
  on:
    branch: master