os: WMF 5

version: '{build}'

environment:
  gitHubToken:
    secure: 
  psGalleryKey:
    secure:

platform:
  - x86
  - Any CPU
  
init:
  - WhoAmI
  
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force
  - ps: Install-Module DevTools -Force

before_build:
  - ps: dt Shortcuts
  - ps: Unnstall-Module DevTools

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup