os: WMF 5

version: '1.1.7.{build}'

platform:
  - x86
#  - x64
  
environment:
  zzz : 2.2.2
  psGalleryKey:
    secure:
  
init:
  - WhoAmI



install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
#  - ps: Install-Module Pester -Force
#  - ps: Install-Module PSScriptAnalyzer -Force
  - ps: Install-Module DevTools -Force

before_build:
  - ps: dt Shortcuts
  - ps: Uninstall-Module DevTools

build_script:
  - ps: dt Build

test_script:
  - ps: dt Test
  
after_test:
  - ps: dt Cleanup
  
build: on

branches:
  only:
    - master
    - dev
    
skip_non_tags: true

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(zzz)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: $(APPVEYOR_PROJECT_NAME)
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true