platform:
  - x64

version: '{build}'

skip_commits:
  message: /(readme|docs)/

init:
  - ps: ('POSH {0}' -f $psVersionTable.psVersion)
  - WhoAmI

install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force | Out-Null
  - ps: Install-Module Pester -RequiredVersion 3.4.3 -Scope CurrentUser -Force
  - ps: Install-Module DevTools -Force

before_test:
  - ps: Get-InstalledModule | Select-Object -Property Name, Version

test_script:
  - ps: |
        dt Install
        dt Test
        dt Build
        dt Cleanup

build: off

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_PROJECT_NAME) release $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: f2QEkAOa73mlQ+LP/dvdg88ByzaXVa21F8M0GgOPzsmU6eLOmrmF5R0jRftFG9DH
  artifact: $(APPVEYOR_PROJECT_NAME)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
